/* eslint-disable @typescript-eslint/naming-convention */
export enum DATA_ACTION_TYPES {
  SET_LOCATION = 'SET_LOCATION',
  SET_CHECK_IN = 'SET_CHECK_IN',
  SET_CHECK_OUT = 'SET_CHECK_OUT',
  SET_GUESTS = 'SET_GUESTS',
  RESET_DATES = 'RESET_DATES',
  RESET_GUESTS = 'RESET_GUESTS',
  INCREASE_GUESTS = 'INCREASE_GUESTS',
  INCREASE_ROOMS = 'INCREASE_CHILDREN',
  DECREASE_GUESTS = 'DECREASE_GUESTS',
  DECREASE_ROOMS = 'DECREASE_CHILDREN',
}

export enum ReservationActionTypes {
  RESET_DATES = 'RESET_DATES',
  SEARCH_DATA = 'SEARCH_DATA',
  TRANSFER_FROM = 'TRANSFER_FROM',
  TRANSFER_TO = 'TRANSFER_TO',
  SET_CHECK_IN = 'SET_CHECK_IN',
  SET_CHECK_OUT = 'SET_CHECK_OUT',
  SET_APART_DATA = 'SET_APART_DATA',
  SET_CONTACT = 'SET_CONTACT',
}
